### ISSUE TITLE
Dirichlet distribution

### ISSUE THREAD

**Issue by Gyx0177** [KarhouTam/pFedLA#2]
If your code uses Dirichlet distribution, the src/server/base.py file will get an error: self.client_id_indices, self.client_num_in_total = get_client_id_indices(self.args.dataset)

**Comment by KarhouTam** [comment]
I think you had partitioned the dataset with `--type user` right? 
About `--type user`, I found bugs in the interface `self.client_id_indices, self.client_num_in_total = get_client_id_indices(self.args.dataset)`. I forgot to write the interface under `--type user` setting.

I personally recommend you to partition under `--type sample`, which means  all clients has their trainset and testset, and that's the scenario of pFedLA experiment.
About codes for `--type user`, I will remove those clearly.

**Comment by Gyx0177** [comment]
Thank you for your answer.
In the case of `--type sample`, can your code ensure that the data is not I.I.D?

**Comment by KarhouTam** [comment]
yea

**Comment by KarhouTam** [comment]
Close this issue due to the inactiveness.
