### ISSUE TITLE
Problem of the training code

### ISSUE THREAD

**Issue by HardworkingLittlequ** [KarhouTam/pFedLA#3]
Hello! We appreciate your great work! I have a question that in 'client/base.py' the function 'def _train(self)' is empty. We could not start training but only evaluating. Could you please help me? Thank you very much!

**Comment by KarhouTam** [comment]
Hello. Thanks for your attention first. 
About your question, sorry I don't get it. `pFedLAClient` has its own `_train()` method:
https://github.com/KarhouTam/pFedLA/blob/e015fe3b217b00100c6b07e8a465be8125a51d10/src/client/pFedLA.py#L50-L73 for client local training. The `_train()` in `ClientBase` is only the abstact method. So when you training the pFedLA, the `_train()` method should replace the abstract one and run properly. 

Currently, I maintain the larger FL benchmark that also includes the pFedLA algo: <https://github.com/KarhouTam/FL-bench>. This pFedLA repo is maintained by me less, so some details about the code may be forgotten. 😂

**Comment by KarhouTam** [comment]
Close the issue due to long-time-no-response.
