### ISSUE TITLE
关于HyperNetwork的

### ISSUE THREAD

**Issue by DashingJ-82** [KarhouTam/pFedLA#4]
你好，关于pFedLA中的HyperNetwork的详细说明，有点模糊，可以介绍一些相关书籍or论文嘛

**Comment by KarhouTam** [comment]
你好。联邦学习和超网络这种技术组合作用的第一篇论文是 pFedHN。你可以在我的另一个仓库 FL bench 中找到关于该算法的论文链接与代码实现。

**Comment by DashingJ-82** [comment]
好的 谢谢
