### ISSUE TITLE
项目运行报错 但是pycharm不报错

### ISSUE THREAD

**Issue by daxu0111** [KarhouTam/pFedLA#5]
![image](https://user-images.githubusercontent.com/85988340/233828266-be7fbfe1-233d-4b2b-8604-e5f208e661d3.png)
![image](https://user-images.githubusercontent.com/85988340/233828346-906024ed-534c-4234-8dd8-c9b96e2baf2f.png)
  File "C:\Users\（省略）\PycharmProjects\pFedLA\src\data\run.py", line 21, in <module>
    from utils.util import DATASETS_DIR
ModuleNotFoundError: No module named 'utils.util'

**Comment by KarhouTam** [comment]
首先感谢你对这个开源工作的关注。以下是我在自己的工作站上的运行截图。
![image](https://user-images.githubusercontent.com/82705454/233829037-78bd2113-7dc0-447b-8e12-7c4b990adb50.png)
感觉应该是环境问题。

我的环境配置：
Ubuntu 22.04
Python 3.9.13

**Comment by daxu0111** [comment]
请问你的requirements中的版本都是多少，我的path依赖一直在出错，但是我已经下载了
![image](https://user-images.githubusercontent.com/85988340/233846320-18f04d77-670e-444f-bbd9-741bcf5a34f1.png)

**Comment by KarhouTam** [comment]
就是 16.6.0 啊。或许你该检查一下你的 python 解释器。

**Comment by daxu0111** [comment]
谢谢，谢谢，是我环境的问题，我已经解决了，请问这个项目的运行结果在哪里，初学者真的什么都不会，对不起🤦‍♂️

**Comment by KarhouTam** [comment]
没多大事，不用对不起。😂
如果需要记录实验结果，https://github.com/KarhouTam/pFedLA/blob/e015fe3b217b00100c6b07e8a465be8125a51d10/src/utils/args.py#L24 这里要设成一个非负数。

你可以直接改动文件或者命令行运行 `pFedLA.py` 时加上  `--log 1`。

小小打个广告。如果你还对别的算法实现感兴趣，可以关注一下我另外一个 repo [FL-bench](https://github.com/KarhouTam/FL-bench)，这个 repo 我仍在持续更新且拥有更多功能。

**Comment by daxu0111** [comment]
![I{6PVYK(WU~MXZT4C`E2{PQ](https://user-images.githubusercontent.com/85988340/233989902-905b9ccf-1b0b-419a-b018-214016835042.png)
谢谢作者，请问这个有什么问题，这个项目需要什么样的算力资源

**Comment by KarhouTam** [comment]
这点我记不清了，起码要 32 G 内存吧我记得。如果算力不够可以稍微把模型改小一点，或者减少 client 数量。具体调参请自行摸索。

**Comment by daxu0111** [comment]
谢谢，我已经能跑起来了，感谢
