### ISSUE TITLE
The seed is not fixed

### ISSUE THREAD

**Issue by julius6868** [KarhouTam/pFedLA#6]
Hi,  I reproduced your code with a fixed seed, but the results obtained from multiple runs remain inconsistent. I am seeking guidance on the possible reasons behind this inconsistency and how to achieve consistent results. Thank you.

**Comment by KarhouTam** [comment]
Hi, @julius6868. First, thanks for your attention to my repo.
The fixing random seed function is shown below.
https://github.com/KarhouTam/pFedLA/blob/c8b505c1edd119cf6bfa4a0bf95406afd5a0de08/src/utils/util.py#L63-L70

Maybe something wrong in the function. You can try some changes like: 
`torch.backends.cudnn.benchmark = False` (This is my mistake, which should always set to `False` for stable reproduction.)
Add `os.environ["PYTHONHASHSEED"] = str(seed)`

Hope my reply has info you wanted.

**Comment by KarhouTam** [comment]
Close issue due to long time no response.
