### ISSUE TITLE
想问一下这个代码在哪运行？

### ISSUE THREAD

**Issue by qianyuyitong** [KarhouTam/pFedLA#8]
pycharm可以吗？还是要在Linux系统上运行？

**Comment by KarhouTam** [comment]
你好。我是在 linux 环境下写的这份代码，所以应该在 linux 上运行是没有问题的。至于 windows 我没试过，感觉应该也可以。至于 pycharm，你可以用任意环境，vscode，甚至纯命令行都行。

**Comment by qianyuyitong** [comment]
好的非常感谢您！还有一个问题，我看代码里没有main.py文件，那这个项目具体怎么执行呢？直接运行run.py文件吗？

**Comment by KarhouTam** [comment]
你可以查看 `scripts` 文件夹下的脚本是运行什么文件来自行修改运行参数。至于运行参数有哪些，还请查阅此项目的 readme

**Comment by qianyuyitong** [comment]
好的，感谢！
