### ISSUE TITLE
想问问大佬我只想使用超网络生成聚合权重矩阵这一部分 应该如何使用呢？

### ISSUE THREAD

**Issue by palem20** [KarhouTam/pFedLA#9]

**Comment by KarhouTam** [comment]
是指一个 module 内只用超网络生成 weight 部分而忽视 bias 部分吗？简单的方法就是在使用超网络之前把客户端模型参数保存一份，在超网络生成的网络参数中，用之前保存下来的模型参数的bias的参数覆盖掉

**Comment by palem20** [comment]
> 是指一个 module 内只用超网络生成 weight 部分而忽视 bias 部分吗？简单的方法就是在使用超网络之前把客户端模型参数保存一份，在超网络生成的网络参数中，用之前保存下来的模型参数的bias的参数覆盖掉

就是说不是在pfedla算法中 超网络会输出一个聚合矩阵吗，通过这个聚合矩阵生成新的客户单模型，目前只想使用这个聚合矩阵，想单独使用这一模块，应该使用源码的哪一部分呢

**Comment by KarhouTam** [comment]
我没记错的话，单个超网络只是针对每个模型中的层输出一个聚合权重向量。可能你说的聚合矩阵指的就是这些聚合权重向量 stack 后的东西？

超网络都是要经过训练的。所以应该不存在单独使用这一模块的说法。
